### ISSUE TITLE
[ffmpeg] Macos 10.12: openh264 not found using pkg-config

### ISSUE THREAD

**Issue by MartinDelille** [bincrafters/community#1047]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **ffmpeg/4.2**
  * Operating System+version: **Macos 10.14**
  * Compiler+version: **apple-clang 10.0.1**
  * Conan version: **conan 1.20.4**
  * Python version: **Python 3.7.5**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

On *MacOS 10.14* I run the following command:

```
conan install .. --profile ../macos_profile --build missing
```

With the following `conanfile.txt`:

```
[requires]
ffmpeg/4.2@bincrafters/stable

[generators]
qmake
```

and the following `macos_profile`:

```
include(default)

[settings]
os.version=10.12
```

Unfortunately, it fails with the following error:

```
ERROR: openh264 not found using pkg-config
```

### Logs (Include/Attach if Applicable)

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=10.0
os=Macos
os.version=10.12
os_build=Macos
[options]
[build_requires]
*: darwin-toolchain/1.0.4@theodelrieu/stable
[env]

WARN: freetype/2.10.0@bincrafters/stable: requirement bzip2/1.0.6@conan/stable overridden by ffmpeg/4.2@bincrafters/stable to bzip2/1.0.8@conan/stable
ffmpeg/4.2@bincrafters/stable: WARN: Package is corrupted, removing folder: /Users/martin/.conan/data/ffmpeg/4.2/bincrafters/stable/package/0c0481eb1d54e41030d78966acd4c61cc682d25f
conanfile.txt: Installing package
Requirements
    OpenSSL/1.1.1c@conan/stable from 'conan-center' - Cache
    bzip2/1.0.8@conan/stable from 'conan-center' - Cache
    ffmpeg/4.2@bincrafters/stable from 'bincrafters' - Cache
    freetype/2.10.0@bincrafters/stable from 'conan-center' - Cache
    lcms/2.9@bincrafters/stable from 'conan-center' - Cache
    libfdk_aac/2.0.0@bincrafters/stable from 'conan-center' - Cache
    libiconv/1.15@bincrafters/stable from 'conan-center' - Cache
    libmp3lame/3.100@bincrafters/stable from 'conan-center' - Cache
    libpng/1.6.37@bincrafters/stable from 'conan-center' - Cache
    libtiff/4.0.9@bincrafters/stable from 'conan-center' - Cache
    libvpx/1.8.0@bincrafters/stable from 'bincrafters' - Cache
    libwebp/1.0.3@bincrafters/stable from 'conan-center' - Cache
    libx264/20190605@bincrafters/stable from 'conan-center' - Cache
    libx265/3.0@bincrafters/stable from 'bincrafters' - Cache
    lzma/5.2.4@bincrafters/stable from 'conan-center' - Cache
    ogg/1.3.3@bincrafters/stable from 'conan-center' - Cache
    openh264/1.7.0@bincrafters/stable from 'bincrafters' - Cache
    openjpeg/2.3.1@bincrafters/stable from 'conan-center' - Cache
    opus/1.3.1@bincrafters/stable from 'conan-center' - Cache
    vorbis/1.3.6@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.1.1c@conan/stable:f792f7ccf1acd7bb5399ab098d53b9af252af834 - Cache
    bzip2/1.0.8@conan/stable:2f6cc0020c8ceeac165d4dbd2287bf07ef617898 - Cache
    ffmpeg/4.2@bincrafters/stable:0c0481eb1d54e41030d78966acd4c61cc682d25f - Build
    freetype/2.10.0@bincrafters/stable:ee78bdd238346e3bc56671b2306ba0f93891a684 - Cache
    lcms/2.9@bincrafters/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
    libfdk_aac/2.0.0@bincrafters/stable:77c54290929cc059e6a1f45a2b845dba895008b3 - Cache
    libiconv/1.15@bincrafters/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
    libmp3lame/3.100@bincrafters/stable:77c54290929cc059e6a1f45a2b845dba895008b3 - Cache
    libpng/1.6.37@bincrafters/stable:1612a5e4b062b1fb18ea2292bbe2917f856fc32e - Cache
    libtiff/4.0.9@bincrafters/stable:1612a5e4b062b1fb18ea2292bbe2917f856fc32e - Cache
    libvpx/1.8.0@bincrafters/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
    libwebp/1.0.3@bincrafters/stable:0e498ccdc2f8d42d9d8b29603ecfa16089256336 - Cache
    libx264/20190605@bincrafters/stable:31e00be25ac2247305c2e5fbe94ab5b5addce9ab - Cache
    libx265/3.0@bincrafters/stable:dd490c6cf4aaa632e9ab3e553cc6b7c208172b64 - Cache
    lzma/5.2.4@bincrafters/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
    ogg/1.3.3@bincrafters/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
    openh264/1.7.0@bincrafters/stable:37589d762416001c3b4dbad50a99e7b410cb0f06 - Cache
    openjpeg/2.3.1@bincrafters/stable:bec9769f48457cc6e6f46c7c2b5bf9855fdc0091 - Cache
    opus/1.3.1@bincrafters/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
    vorbis/1.3.6@bincrafters/stable:54e7b05b523de79292fd0c33b8a8b87a03be2390 - Cache
    zlib/1.2.11@conan/stable:7b575b499ccd449faf97006981bf85a6191e00f2 - Cache
Build requirements
    darwin-toolchain/1.0.4@theodelrieu/stable from 'conan-center' - Cache
    yasm_installer/1.3.0@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    darwin-toolchain/1.0.4@theodelrieu/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    yasm_installer/1.3.0@bincrafters/stable:743cf0321be3152777da4d05247a66d1552e70a2 - Cache

bzip2/1.0.8@conan/stable: Already installed!
darwin-toolchain/1.0.4@theodelrieu/stable: Already installed!
lcms/2.9@bincrafters/stable: Already installed!
libfdk_aac/2.0.0@bincrafters/stable: Already installed!
libiconv/1.15@bincrafters/stable: Already installed!
libmp3lame/3.100@bincrafters/stable: Already installed!
libvpx/1.8.0@bincrafters/stable: Already installed!
libwebp/1.0.3@bincrafters/stable: Already installed!
libx264/20190605@bincrafters/stable: Already installed!
libx265/3.0@bincrafters/stable: Already installed!
lzma/5.2.4@bincrafters/stable: Already installed!
ogg/1.3.3@bincrafters/stable: Already installed!
openh264/1.7.0@bincrafters/stable: Already installed!
opus/1.3.1@bincrafters/stable: Already installed!
yasm_installer/1.3.0@bincrafters/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
OpenSSL/1.1.1c@conan/stable: Already installed!
libpng/1.6.37@bincrafters/stable: Already installed!
libtiff/4.0.9@bincrafters/stable: Already installed!
vorbis/1.3.6@bincrafters/stable: Already installed!
freetype/2.10.0@bincrafters/stable: Already installed!
openjpeg/2.3.1@bincrafters/stable: Already installed!
ffmpeg/4.2@bincrafters/stable: Applying build-requirement: darwin-toolchain/1.0.4@theodelrieu/stable
ffmpeg/4.2@bincrafters/stable: Applying build-requirement: yasm_installer/1.3.0@bincrafters/stable
ffmpeg/4.2@bincrafters/stable: WARN: Build folder is dirty, removing it: /Users/martin/.conan/data/ffmpeg/4.2/bincrafters/stable/build/0c0481eb1d54e41030d78966acd4c61cc682d25f
ffmpeg/4.2@bincrafters/stable: Copying sources to build folder
ffmpeg/4.2@bincrafters/stable: Building your package in /Users/martin/.conan/data/ffmpeg/4.2/bincrafters/stable/build/0c0481eb1d54e41030d78966acd4c61cc682d25f
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created darwin-toolchain.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created yasm_installer.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created lzma.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libiconv.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created freetype.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created openjpeg.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created openh264.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created vorbis.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created opus.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libx264.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libx265.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libvpx.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libmp3lame.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libfdk_aac.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libwebp.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created OpenSSL.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created bzip2.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libpng.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created lcms.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created libtiff.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created ogg.pc
ffmpeg/4.2@bincrafters/stable: Generator pkg_config created zlib.pc
ffmpeg/4.2@bincrafters/stable: Calling build()
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file libwebp.pc
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file libwebpmux.pc
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file libwebpdecoder.pc
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file libwebpdemux.pc
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file vorbisfile.pc
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file vorbis.pc
ffmpeg/4.2@bincrafters/stable: WARN: copy .pc file vorbisenc.pc
ffmpeg/4.2@bincrafters/stable: Calling:
 > ./configure '--prefix=/Users/martin/.conan/data/ffmpeg/4.2/bincrafters/stable/package/0c0481eb1d54e41030d78966acd4c61cc682d25f' '--disable-doc' '--disable-programs' '--disable-shared' '--enable-static' '--pkg-config-flags=--static' '--enable-pic' '--enable-postproc' '--enable-zlib' '--enable-bzlib' '--enable-lzma' '--enable-iconv' '--enable-libfreetype' '--enable-libopenjpeg' '--enable-libopenh264' '--enable-libvorbis' '--enable-libopus' '--disable-libzmq' '--disable-sdl2' '--enable-libx264' '--enable-libx265' '--enable-libvpx' '--enable-libmp3lame' '--enable-libfdk-aac' '--enable-libwebp' '--enable-openssl' '--enable-gpl' '--enable-nonfree' '--enable-appkit' '--enable-avfoundation' '--enable-coreimage' '--enable-audiotoolbox' '--enable-videotoolbox' '--disable-securetransport' '--disable-cuda' '--disable-cuvid' '--bindir=${prefix}/bin' '--libdir=${prefix}/lib'
ERROR: openh264 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
ffmpeg/4.2@bincrafters/stable:
ffmpeg/4.2@bincrafters/stable: ERROR: Package '0c0481eb1d54e41030d78966acd4c61cc682d25f' build failed
ffmpeg/4.2@bincrafters/stable: WARN: Build folder /Users/martin/.conan/data/ffmpeg/4.2/bincrafters/stable/build/0c0481eb1d54e41030d78966acd4c61cc682d25f
ERROR: ffmpeg/4.2@bincrafters/stable: Error in build() method, line 231
	self.build_configure()
while calling 'build_configure', line 329
	env_build.configure(args=args, build=False, host=False, target=False)
	ConanException: Error 1 while executing ./configure '--prefix=/Users/martin/.conan/data/ffmpeg/4.2/bincrafters/stable/package/0c0481eb1d54e41030d78966acd4c61cc682d25f' '--disable-doc' '--disable-programs' '--disable-shared' '--enable-static' '--pkg-config-flags=--static' '--enable-pic' '--enable-postproc' '--enable-zlib' '--enable-bzlib' '--enable-lzma' '--enable-iconv' '--enable-libfreetype' '--enable-libopenjpeg' '--enable-libopenh264' '--enable-libvorbis' '--enable-libopus' '--disable-libzmq' '--disable-sdl2' '--enable-libx264' '--enable-libx265' '--enable-libvpx' '--enable-libmp3lame' '--enable-libfdk-aac' '--enable-libwebp' '--enable-openssl' '--enable-gpl' '--enable-nonfree' '--enable-appkit' '--enable-avfoundation' '--enable-coreimage' '--enable-audiotoolbox' '--enable-videotoolbox' '--disable-securetransport' '--disable-cuda' '--disable-cuvid' '--bindir=${prefix}/bin' '--libdir=${prefix}/lib'
```

**Comment by Croydon** [comment]
Hi there!

Any chance that you could re-try this with `ffmpeg/4.2.1@bincrafters/stable`?

**Comment by MartinDelille** [comment]
Now I have the following error:

```
...
libwebp/1.0.3: Downloaded recipe revision 0
ERROR: Failed requirement 'openssl/1.1.1d' from 'ffmpeg/4.2.1@bincrafters/stable'
ERROR: Requested 'openssl/1.1.1d' but found case incompatible 'OpenSSL'
Case insensitive filesystem can't manage this
```

**Comment by Croydon** [comment]
Sorry about that, this is the pain of migrating things to Conan Center Index.

If you can, please remove the uppercase `OpenSSL/1.x.y@conan/stable` from your systems and replace it everywhere with the lowercase version `openssl/1.x.y` (no user/channel)

**Comment by MartinDelille** [comment]
Ok since I don't use yet a lot conan yet I removed the whole `~/.conan` folder and add again the bincrafters repository.

I now have the following error:

```
...
 created lcms.pc
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created tiff.pc
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created ogg.pc
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created zlib.pc
ffmpeg/4.2.1@bincrafters/stable: Calling build()
ffmpeg/4.2.1@bincrafters/stable:
ffmpeg/4.2.1@bincrafters/stable: ERROR: Package 'fc0fc3f9103643c7068a7fac9d776a9cbfc2b43d' build failed
ffmpeg/4.2.1@bincrafters/stable: WARN: Build folder /Users/martin/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/fc0fc3f9103643c7068a7fac9d776a9cbfc2b43d
ERROR: ffmpeg/4.2.1@bincrafters/stable: Error in build() method, line 228
	self.build_configure()
while calling 'build_configure', line 240
	shutil.move("libx264.pc", "x264.pc")
	FileNotFoundError: [Errno 2] No such file or directory: 'libx264.pc'
```

**Comment by Croydon** [comment]
@ericLemanissier Can we merge https://github.com/bincrafters/conan-ffmpeg/commit/d061153e2d31499950e6a280b0326a7f5f1595f8 into stable?

**Comment by ericLemanissier** [comment]
@Croydon yes!

**Comment by Croydon** [comment]
Merged

@MartinDelille Please try again with

`conan install .. --profile ../macos_profile --build missing --update`

(notice `--update` so that it refreshes your local copy of the recipe)

**Comment by MartinDelille** [comment]
```
...
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created libpng.pc
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created ogg.pc
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created zlib.pc
ffmpeg/4.2.1@bincrafters/stable: Calling build()
ffmpeg/4.2.1@bincrafters/stable:
ffmpeg/4.2.1@bincrafters/stable: ERROR: Package '31b493cef9b707d1bba18b3425eaf3a12653bc80' build failed
ffmpeg/4.2.1@bincrafters/stable: WARN: Build folder /Users/martin/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/31b493cef9b707d1bba18b3425eaf3a12653bc80
ERROR: ffmpeg/4.2.1@bincrafters/stable: Error in build() method, line 228
	self.build_configure()
while calling 'build_configure', line 233
	shutil.move("freetype.pc", "freetype2.pc")
	FileNotFoundError: [Errno 2] No such file or directory: 'freetype.pc'
```

**Comment by ericLemanissier** [comment]
fixed with https://github.com/bincrafters/conan-ffmpeg/commit/b7f4772e32543bebec74e76e96bf7cbdf33edd93 It's a matter of CI time before it is available on the stable branch

**Comment by ericLemanissier** [comment]
@MartinDelille it should be ok now

**Comment by MartinDelille** [comment]
I don't have my development machine anymore because it is on maintenance.

I retried on my personal computer:

```bash
$ conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=9.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

Unfortunately I still have an error:
```
$ conan install .. --profile ../macos_profile --build missing --update
...
ffmpeg/4.2.1@bincrafters/stable: Generator pkg_config created zlib.pc
ffmpeg/4.2.1@bincrafters/stable: Calling build()
ffmpeg/4.2.1@bincrafters/stable:
ffmpeg/4.2.1@bincrafters/stable: ERROR: Package 'b15fd9d925ee884889e27f2c88a4b9ca4f0cd2c0' build failed
ffmpeg/4.2.1@bincrafters/stable: WARN: Build folder /Users/martin/.conan/data/ffmpeg/4.2.1/bincrafters/stable/build/b15fd9d925ee884889e27f2c88a4b9ca4f0cd2c0
ERROR: ffmpeg/4.2.1@bincrafters/stable: Error in build() method, line 228
	self.build_configure()
while calling 'build_configure', line 236
	shutil.move("openjpeg.pc", "libopenjp2.pc")
	FileNotFoundError: [Errno 2] No such file or directory: 'openjpeg.pc'
```

**Comment by ericLemanissier** [comment]
indeed, CCI's openjpeg was modified yesterday. ffmpeg's updated recipe is now on bintray, if you want to try again.

**Comment by MartinDelille** [comment]
It worked! Nice job! 😄

**Comment by Croydon** [comment]
Thanks for keep trying!

We might run into such problems for a while longer until we have migrated more to the Conan Center Index and figured everything out

**Comment by MartinDelille** [comment]
No problem!

I'm very interested into using conan in my project even if I don't find it very mature yet for macos/ios so I'll be happy to go on with testing.
