### ISSUE TITLE
Inclusion Request: libmikmod

### ISSUE THREAD

**Issue by sixten-hilborn** [bincrafters/community#596]
### Package Details
  * Package Name: **libmikmod**
  * Operating Systems+versions: **ALL supported by the Bincrafters default template**
  * Compiler support: **ALL supported by the Bincrafters default template**
  * Conan recipe repository: **https://github.com/sixten-hilborn/conan-libmikmod**

### Inclusion request
  * [x] I want that my Conan recipe is getting included into the Bincrafters organisation
  * [x] I understand that if my request is accepted we are cloning your repository with all its history into Bincrafters, adapt some configurations and meta data if needed, and publishing it under the Bincrafters name and accounts
  * [x] I have used the Bincrafters templates to develop my Conan recipe - https://github.com/bincrafters/conan-templates
  * [x] My Conan recipe and all parts of it are licensed under the MIT license - https://choosealicense.com/licenses/mit/
    * Bincrafters are releasing all recipes under MIT license. If you want to have your recipe within Bincrafters we kindly ask you to do the same
    * it is okay if your test_package contains code from the upstream project under the upstream project's license, as long as it is clearly mentioned within the test_package files
  * [x] My Conan recipe covers (at least) the latest stable version which is available for the package
  * [x] I know that my Conan recipe is working on all operating system and compilers mentioned above right now
    * if not: please provide here links to your CI platforms and / or build logs and describe the problems you encounter
  * [x] I'm willing to help to maintain the recipe even after it is included into Bincrafters

### Checklist for the Bincrafters team
  * [x] There is no such Conan package yet in conan-center, conan-community or Bincrafters
  * [x] The project is either popular or deserves to be maintained for another good reason (we can't package every single project out there)
  * [x] [bincrafters-conventions](https://github.com/bincrafters/bincrafters-conventions) reports no complains; the recipe fulfills our general quality requirements and conventions
  * [x] The recipe is cloned into our organisation; CI is enabled and configurated and succeeds
  * [x] There is a branch protection rule for `stable/*` branches, which requires a pull request with at least one approval first before things can get published
  * Considering granding the inclusion request author push rights to the recipe repository (there is no guarantee that everyone is getting push rights, we decide this on a case-to-case base)

**Comment by Croydon** [comment]
Hi! Thanks for your work, libmikmod seems like a nice addition 😄 

  * I have cloned the repository and enabled CI: https://github.com/bincrafters/conan-libmikmod
  * Please note for further recipes that tools.get() should always have a sha256 checksum to add another layer of security. I have added it now
  * [ ] The test_package is not good right now, can you think of any tests which actually execute the build library and which can run automatically?

**Comment by Croydon** [comment]
@sixten-hilborn Are you going to work on the remaining issues?

**Comment by sixten-hilborn** [comment]
Yes, I've been busy lately, but I just pushed some fixes to `testing/`.

**Comment by Croydon** [comment]
Revisiting this now. CI is still failing due to system dependencies.

Could you please have a look again? @sixten-hilborn

**Comment by Croydon** [comment]
Is someone familiar with `libpulse-simple`? 
the package already installs `libpulse-dev` via apt, but `libpulse-simple` still can't be found https://travis-ci.com/bincrafters/conan-libmikmod/jobs/188958516#L1095

**Comment by SSE4** [comment]
I am on it now, as it's dependency on `sdl2_mixer` library

**Comment by SSE4** [comment]
@Croydon I have fixed problems with pulse audio, I think we're now good with it
